caches:
 mapquest_aerial_cache:
   sources: [mapquest_aerial_tile]
   grids: [epsg3857]

sources:
 mapquest_aerial_tile:
   type: tile
   grid: epsg3857nw
   #coverage:
      #bbox: [-20037508.342789236,-20037508.342789236,20037508.342789236,20037508.342789236]
      #bbox_srs: 'EPSG:3857'
   url: http://oatile1.mqcdn.com/tiles/1.0.0/sat/%(tms_path)s.jpg
   on_error:
    204:
      response: transparent
      cache: True
    502:
      response: '#ede9e3'
      cache: False
    other:
      response: transparent
      cache: False
