
caches:
  atgrazogd_aerial_cache:
    grids: [epsg3857]
    sources: [atgrazogd_aerial_wms]
    link_single_color_images: true

sources:
  atgrazogd_aerial_wms:
    type: wms
    req:
      url: http://geodaten1.graz.at/ArcGIS_Graz/services/Extern/LUFTBILD_WMS/MapServer/WMSServer
      layers: 1
      transparent: true
    min_res: 611.49622628141
    coverage:
      bbox: [15.34474, 47.00782, 15.53929, 47.14237]
      bbox_srs: 'EPSG:4326'
    image:
      transparent_color: '#ffffff'

