
caches:
  atvogisogd_aerial_cache:
    grids: [epsg3857]
    sources: [atvogisogd_aerial_wms]
    link_single_color_images: true

sources:
  atvogisogd_aerial_wms:
    type: wms
    #supported_srs: ['EPSG:31254']
    #supported_srs: ['EPSG:25832']
    #supported_srs: ['EPSG:4326','EPSG:25832']
    supported_srs: ['EPSG:4326']

    min_res: 611.49622628141
    image:
      transparent_color: '#ffffff'
      transparent_color_tolerance: 20
    coverage:
      bbox: [9.40879, 46.83183, 10.26317, 47.61083]
      bbox_srs: 'EPSG:4326'
    req:
      url: http://vogis.cnv.at/mapserver/mapserv?map=i_luftbilder_r_wms.map
      layers: ef2009_25cmm
      transparent: true


