grids:
 epsg4326:
   srs: EPSG:4326
   num_levels: 20

 epsg3857:
   #base: GLOBAL_MERCATOR
   srs: EPSG:3857
   num_levels: 20

 epsg3857nw:
   base: GLOBAL_MERCATOR
   #srs: EPSG:3857
   num_levels: 20
   origin: nw
